[package]
name = "user-agents"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.13"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
thiserror = "2.0.12"
